# Generated by Django 5.2.7 on 2025-11-29 21:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_abonnes_requis', models.IntegerField(default=0)),
                ('date_limite_candidature', models.DateTimeField()),
                ('date_debut_campagne', models.DateField(blank=True, null=True)),
                ('date_fin_campagne', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('active', 'Active'), ('fermee', 'Fermée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('total_candidatures', models.IntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campagnes',
            },
        ),
        migrations.CreateModel(
            name='PlateformeSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('url_icone', models.CharField(blank=True, max_length=500, null=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plateformes_sociales',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('type_utilisateur', models.CharField(choices=[('influenceur', 'Influenceur'), ('entreprise', 'Entreprise')], max_length=20)),
                ('est_actif', models.BooleanField(default=True)),
                ('est_verifie', models.BooleanField(default=False)),
                ('tentatives_connexion_echouees', models.IntegerField(default=0)),
                ('verrouille_jusqu_a', models.DateTimeField(blank=True, null=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DomaineExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': "Domaines d'expertise",
                'db_table': 'domaines_expertise',
                'indexes': [models.Index(fields=['slug'], name='domaines_ex_slug_a38afb_idx')],
            },
        ),
        migrations.CreateModel(
            name='CampagneDomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campagne')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.domaineexpertise')),
            ],
            options={
                'db_table': 'campagne_domaines',
            },
        ),
        migrations.AddField(
            model_name='campagne',
            name='domaines',
            field=models.ManyToManyField(related_name='campagnes', through='api.CampagneDomaine', to='api.domaineexpertise'),
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('url_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('site_web', models.CharField(blank=True, max_length=500, null=True)),
                ('secteur', models.CharField(blank=True, max_length=100, null=True)),
                ('taille_entreprise', models.CharField(blank=True, choices=[('startup', 'Startup'), ('pme', 'PME'), ('grande_entreprise', 'Grande Entreprise'), ('agence', 'Agence')], max_length=20, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entreprises',
            },
        ),
        migrations.AddField(
            model_name='campagne',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entreprise'),
        ),
        migrations.CreateModel(
            name='Influenceur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=100)),
                ('photo_profil', models.CharField(blank=True, max_length=500, null=True)),
                ('biographie', models.TextField(blank=True, max_length=500, null=True)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('pourcentage_completion_profil', models.IntegerField(default=0)),
                ('taux_acceptation', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_candidatures', models.IntegerField(default=0)),
                ('candidatures_acceptees', models.IntegerField(default=0)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influenceur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'influenceurs',
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('retiree', 'Retirée')], default='en_attente', max_length=20)),
                ('message_motivation', models.TextField(blank=True, max_length=500, null=True)),
                ('prix_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collaborations_passees', models.TextField(blank=True, null=True)),
                ('candidate_le', models.DateTimeField(auto_now_add=True)),
                ('evaluee_le', models.DateTimeField(blank=True, null=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campagne')),
                ('evaluee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_evaluees', to=settings.AUTH_USER_MODEL)),
                ('influenceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.influenceur')),
            ],
            options={
                'db_table': 'candidatures',
            },
        ),
        migrations.CreateModel(
            name='InfluenceurExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.domaineexpertise')),
                ('influenceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.influenceur')),
            ],
            options={
                'db_table': 'influenceur_expertise',
            },
        ),
        migrations.AddField(
            model_name='influenceur',
            name='domaines',
            field=models.ManyToManyField(related_name='influenceurs', through='api.InfluenceurExpertise', to='api.domaineexpertise'),
        ),
        migrations.CreateModel(
            name='InfluenceurTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_par_post', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_par_story', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_par_video', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('est_negociable', models.BooleanField(default=True)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('influenceur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='api.influenceur')),
            ],
            options={
                'db_table': 'influenceur_tarifs',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nouvelle_campagne', 'Nouvelle campagne'), ('reponse_candidature', 'Réponse candidature'), ('message', 'Message'), ('systeme', 'Système')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type_entite_liee', models.CharField(blank=True, choices=[('campagne', 'Campagne'), ('candidature', 'Candidature'), ('utilisateur', 'Utilisateur')], max_length=20, null=True)),
                ('id_entite_liee', models.IntegerField(blank=True, null=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='InfluenceurPlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_abonnes', models.IntegerField()),
                ('taux_engagement', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vues_moyennes', models.IntegerField(blank=True, null=True)),
                ('url_profil', models.CharField(blank=True, max_length=500, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('influenceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.influenceur')),
                ('plateforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plateformesociale')),
            ],
            options={
                'db_table': 'influenceur_plateformes',
            },
        ),
        migrations.CreateModel(
            name='CampagnePlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campagne')),
                ('plateforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plateformesociale')),
            ],
            options={
                'db_table': 'campagne_plateformes',
            },
        ),
        migrations.AddField(
            model_name='campagne',
            name='plateformes',
            field=models.ManyToManyField(related_name='campagnes', through='api.CampagnePlateforme', to='api.plateformesociale'),
        ),
        migrations.CreateModel(
            name='RechercheSauvegardee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_recherche', models.CharField(max_length=100)),
                ('criteres_recherche', models.JSONField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('influenceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.influenceur')),
            ],
            options={
                'db_table': 'recherches_sauvegardees',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='utilisateur_email_1cb90f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['type_utilisateur'], name='utilisateur_type_ut_840549_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campagnedomaine',
            unique_together={('campagne', 'domaine')},
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['nom_entreprise'], name='entreprises_nom_ent_7cb869_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['statut'], name='candidature_statut_f5071e_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['candidate_le'], name='candidature_candida_356279_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidature',
            unique_together={('campagne', 'influenceur')},
        ),
        migrations.AlterUniqueTogether(
            name='influenceurexpertise',
            unique_together={('influenceur', 'domaine')},
        ),
        migrations.AddIndex(
            model_name='influenceur',
            index=models.Index(fields=['pourcentage_completion_profil'], name='influenceur_pourcen_ccfb23_idx'),
        ),
        migrations.AddIndex(
            model_name='influenceur',
            index=models.Index(fields=['localisation'], name='influenceur_localis_253d95_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['utilisateur', 'est_lue'], name='notificatio_utilisa_7a669e_idx'),
        ),
        migrations.AddIndex(
            model_name='influenceurplateforme',
            index=models.Index(fields=['nombre_abonnes'], name='influenceur_nombre__c60b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='influenceurplateforme',
            index=models.Index(fields=['influenceur', 'nombre_abonnes'], name='influenceur_influen_b96629_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='influenceurplateforme',
            unique_together={('influenceur', 'plateforme')},
        ),
        migrations.AlterUniqueTogether(
            name='campagneplateforme',
            unique_together={('campagne', 'plateforme')},
        ),
        migrations.AddIndex(
            model_name='campagne',
            index=models.Index(fields=['statut'], name='campagnes_statut_e29d35_idx'),
        ),
        migrations.AddIndex(
            model_name='campagne',
            index=models.Index(fields=['date_limite_candidature'], name='campagnes_date_li_45aec0_idx'),
        ),
        migrations.AddIndex(
            model_name='campagne',
            index=models.Index(fields=['cree_le'], name='campagnes_cree_le_061c54_idx'),
        ),
    ]
