# Generated by Django 5.2.7 on 2025-11-29 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, db_column='cree_le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(db_column='date_joined', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='derniere_connexion',
            field=models.DateTimeField(blank=True, db_column='derniere_connexion', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_column='email', max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='est_actif',
            field=models.BooleanField(db_column='est_actif', default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='est_verifie',
            field=models.BooleanField(db_column='est_verifie', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, db_column='first_name', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_column='is_staff', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(db_column='is_superuser', default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, db_column='last_login', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, db_column='last_name', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True, db_column='modifie_le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='mot_de_passe_hash', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='tentatives_connexion_echouees',
            field=models.IntegerField(db_column='tentatives_connexion_echouees', default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_utilisateur',
            field=models.CharField(choices=[('influenceur', 'Influenceur'), ('entreprise', 'Entreprise')], db_column='type_utilisateur', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_column='username', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verrouille_jusqu_a',
            field=models.DateTimeField(blank=True, db_column='verrouille_jusqu_a', null=True),
        ),
    ]
