# Generated by Django 5.2.7 on 2025-12-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='idx_email',
            old_name='utilisateur_email_1cb90f_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='idx_type_utilisateur',
            old_name='utilisateur_type_ut_840549_idx',
        ),
    ]
